// src/components/shared/Footer.vue
<template>
  <footer class="footer">
    <div class="container">
      <div class="footer-content">
        <!-- Logo and Company Info -->
        <div class="footer-logo-section">
          <img src="https://www.itforyouthghana.org/wp-content/uploads/2024/04/Asset-2-1-2048x2027.png" alt="IT For Youth Ghana" class="footer-logo">
          <h3 class="company-name">IT For Youth Ghana</h3>
          <p class="footer-tagline">Empowering Ghana's youth through technology</p>
        </div>

        <!-- Address -->
        <div class="footer-address">
          <h4>Address</h4>
          <p>GECKO STREET L539</p>
          <p>Kwabenya, Musuku</p>
          <p>Accra, Ghana</p>
          <p class="contact-info">
            <strong>Email:</strong> info@itforyouthghana.org<br>
            <strong>Phone:</strong> +233 59 624 4834
          </p>
        </div>

        <!-- Social Media -->
        <div class="footer-social">
          <h4>Follow Us</h4>
          <div class="social-links">
            <a href="https://www.linkedin.com/company/it-for-youth-ghana-foundation" class="social-link linkedin" target="_blank" aria-label="LinkedIn">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
              </svg>
            </a>
            
            <a href="https://www.instagram.com/itforyouthghana/" class="social-link instagram" target="_blank" aria-label="Instagram">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
              </svg>
            </a>
            
            <a href="https://web.facebook.com/itforyouthghanacollege" class="social-link facebook" target="_blank" aria-label="Facebook">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
              </svg>
            </a>
          </div>
        </div>
      </div>

      <!-- Copyright -->
      <div class="footer-bottom">
        <p class="footer-copyright">&copy; 2025 IT For Youth Ghana Foundation. All rights reserved.</p>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
</script>

<style scoped>
.footer {
  background: linear-gradient(135deg, rgba(15, 20, 25, 0.98) 0%, rgba(26, 35, 56, 0.95) 100%);
  color: white;
  padding: 3rem 0 2rem;
  margin-top: auto;
  border-top: 1px solid rgba(140, 181, 218, 0.2);
  position: relative;
  overflow: hidden;
  width: 100vw;
  left: 50%;
  right: 50%;
  margin-left: -50vw;
  margin-right: -50vw;
}

.footer::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: 
    radial-gradient(circle at 50% 0%, rgba(3, 94, 172, 0.1) 0%, transparent 50%),
    radial-gradient(circle at 20% 100%, rgba(140, 181, 218, 0.05) 0%, transparent 50%);
  pointer-events: none;
}

.container {
  max-width: 1400px;
  margin: 0 auto;
  padding: 0 3rem;
  position: relative;
  z-index: 2;
}

.footer-content {
  display: grid;
  grid-template-columns: 2fr 1.2fr 1fr;
  gap: 3rem;
  align-items: start;
  margin-bottom: 2.5rem;
}

.footer-logo-section {
  text-align: left;
}

.footer-logo {
  height: 60px;
  width: auto;
  object-fit: contain;
  margin-bottom: 1rem;
  filter: brightness(1.1);
}

.company-name {
  color: white;
  font-size: 1.8rem;
  font-weight: 700;
  margin: 0 0 0.5rem 0;
  letter-spacing: -0.01em;
}

.footer-tagline {
  color: #8cb5da;
  font-size: 1.1rem;
  margin: 0;
  line-height: 1.5;
}

.footer-address h4,
.footer-social h4 {
  color: white;
  font-size: 1.2rem;
  font-weight: 600;
  margin: 0 0 1rem 0;
  letter-spacing: 0.02em;
}

.footer-address p {
  color: rgba(249, 248, 249, 0.8);
  margin: 0 0 0.3rem 0;
  line-height: 1.5;
  font-size: 0.95rem;
}

.contact-info {
  margin-top: 1.2rem !important;
  font-size: 0.9rem;
  line-height: 1.6;
}

.contact-info strong {
  color: #8cb5da;
}

.social-links {
  display: flex;
  gap: 1rem;
  align-items: center;
}

.social-link {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 48px;
  height: 48px;
  border-radius: 12px;
  background: rgba(255, 255, 255, 0.08);
  color: rgba(249, 248, 249, 0.8);
  text-decoration: none;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  border: 1px solid rgba(140, 181, 218, 0.2);
  backdrop-filter: blur(10px);
}

.social-link:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);
  border-color: rgba(140, 181, 218, 0.4);
}

.social-link.linkedin:hover {
  background: #0077b5;
  color: white;
}

.social-link.instagram:hover {
  background: linear-gradient(45deg, #f09433 0%, #e6683c 25%, #dc2743 50%, #cc2366 75%, #bc1888 100%);
  color: white;
}

.social-link.facebook:hover {
  background: #1877f2;
  color: white;
}

.footer-bottom {
  text-align: center;
  padding-top: 1.5rem;
  border-top: 1px solid rgba(140, 181, 218, 0.2);
}

.footer-copyright {
  color: #8cb5da;
  font-size: 0.9rem;
  margin: 0;
  opacity: 0.8;
}

@media (max-width: 1024px) {
  .footer-content {
    grid-template-columns: 1fr 1fr;
    gap: 3rem;
  }
  
  .footer-logo-section {
    grid-column: 1 / -1;
    text-align: center;
    margin-bottom: 2rem;
  }
}

@media (max-width: 768px) {
  .footer {
    padding: 3rem 0 2rem;
  }
  
  .container {
    padding: 0 1.5rem;
  }
  
  .footer-content {
    grid-template-columns: 1fr;
    gap: 2.5rem;
    text-align: center;
  }
  
  .footer-logo-section {
    text-align: center;
  }
  
  .footer-address,
  .footer-social {
    text-align: center;
  }
  
  .social-links {
    justify-content: center;
  }
}

@media (max-width: 480px) {
  .footer {
    padding: 2rem 0 1.5rem;
  }
  
  .container {
    padding: 0 1rem;
  }
  
  .footer-content {
    gap: 2rem;
  }
  
  .social-link {
    width: 44px;
    height: 44px;
  }
  
  .company-name {
    font-size: 1.5rem;
  }
  
  .footer-tagline {
    font-size: 1rem;
  }
}
</style>

// src/components/Footer.tsx
import React from 'react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { content } from '../data/content'

const Footer: React.FC = () => {
  const footerLinks = {
    programs: [
      'Tech Outreach Initiative',
      'Girls in Tech Programs',
      'Rural Tech Connect',
      'Code Impact Challenge',
      'School Workshops'
    ],
    about: [
      'Our Mission',
      'Our Vision',
      'Impact Stories',
      'Team',
      'Partners'
    ],
    getInvolved: [
      'Volunteer',
      'Donate',
      'Corporate Partnership',
      'Mentorship',
      'Join a Program'
    ]
  }

  // CHANGED: Nur Original Social Media Logos - LinkedIn und Facebook wie spezifiziert
  const socialLinks = [
    { 
      name: 'LinkedIn', 
      href: 'https://linkedin.com/company/it-for-youth-ghana',
      color: 'bg-blue-600 hover:bg-blue-700',
      icon: (
        <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
          <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
        </svg>
      )
    },
    { 
      name: 'Facebook', 
      href: 'https://facebook.com/ityouthghana',
      color: 'bg-blue-500 hover:bg-blue-600',
      icon: (
        <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
          <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
        </svg>
      )
    }
  ]

  return (
    <footer className="bg-primary relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-secondary/10 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 right-1/4 w-80 h-80 bg-accent/10 rounded-full blur-3xl"></div>
      </div>

      <div className="container relative z-10">
        {/* UPDATED: Bereinigte Footer-Struktur - max 3 Spalten */}
        <div className="py-16">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12 mb-12">
            {/* Logo and description */}
            <div>
              <motion.div 
                className="flex items-center mb-6"
                whileHover={{ scale: 1.05 }}
              >
                <img 
                  src="/images/logo/logo.png" 
                  alt="IT for Youth Ghana" 
                  className="h-16 w-auto object-contain"
                />
              </motion.div>
              
              <p className="text-white/90 leading-relaxed mb-6">
                {content.seo.description.split('.')[0]}. Building the next generation of tech leaders.
              </p>
              
              <div className="space-y-2 text-white/90">
                <p>E-Mail: {content.contact.email}</p>
                <p>Phone: {content.contact.phone}</p>
                <p>Address: {content.contact.address}</p>
              </div>
            </div>

            {/* Navigation */}
            <div>
              <h3 className="heading-sm text-white mb-6">Navigation</h3>
              <ul className="space-y-3">
                <motion.li 
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.1 }}
                >
                  <Link 
                    to="/about" 
                    onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                    className="text-white/80 hover:text-secondary transition-colors duration-300 block"
                  >
                    About
                  </Link>
                </motion.li>
                <motion.li 
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.2 }}
                >
                  <Link 
                    to="/programs" 
                    onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                    className="text-white/80 hover:text-secondary transition-colors duration-300 block"
                  >
                    Programs
                  </Link>
                </motion.li>
                <motion.li 
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.3 }}
                >
                  <Link 
                    to="/impact" 
                    onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                    className="text-white/80 hover:text-secondary transition-colors duration-300 block"
                  >
                    Impact
                  </Link>
                </motion.li>
                <motion.li 
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.4 }}
                >
                  <Link 
                    to="/partners" 
                    onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                    className="text-white/80 hover:text-secondary transition-colors duration-300 block"
                  >
                    Partners
                  </Link>
                </motion.li>
                <motion.li 
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.5 }}
                >
                  <Link 
                    to="/volunteer" 
                    onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                    className="text-white/80 hover:text-secondary transition-colors duration-300 block"
                  >
                    Volunteer
                  </Link>
                </motion.li>
                <motion.li 
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.6 }}
                >
                  <Link 
                    to="/contact" 
                    onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                    className="text-white/80 hover:text-secondary transition-colors duration-300 block"
                  >
                    Contact
                  </Link>
                </motion.li>
              </ul>
            </div>

            {/* Socials */}
            <div>
              <h3 className="heading-sm text-white mb-6">Follow Us</h3>
              <div className="flex space-x-4 mb-6">
                {socialLinks.map((social, index) => (
                  <motion.a
                    key={social.name}
                    href={social.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={`w-12 h-12 ${social.color} rounded-xl flex items-center justify-center text-white transition-all duration-300 shadow-lg hover:shadow-xl`}
                    whileHover={{ scale: 1.05, y: -2 }}
                    whileTap={{ scale: 0.95 }}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                    title={`Follow us on ${social.name}`}
                  >
                    {social.icon}
                  </motion.a>
                ))}
              </div>
              
              <p className="text-white/90 text-sm">
                Stay connected with our latest updates and success stories.
              </p>
            </div>
          </div>

          {/* Newsletter signup */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="glass rounded-2xl p-8 mb-12"
          >
            <div className="text-center">
              <h3 className="heading-md text-white mb-4">Stay Connected</h3>
              <p className="text-white/90 mb-6 max-w-2xl mx-auto">
                Get the latest updates on our programs, success stories, and opportunities to get involved.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
                <input
                  type="email"
                  placeholder="Enter your email"
                  className="flex-1 px-4 py-3 rounded-lg bg-white/10 border border-white/20 text-white placeholder-white/50 focus:outline-none focus:border-secondary transition-colors duration-300"
                />
                <motion.button
                  className="bg-accent hover:bg-accent/90 text-white px-8 py-3 rounded-lg font-medium transition-colors duration-300"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  Subscribe
                </motion.button>
              </div>
            </div>
          </motion.div>

          {/* UPDATED: Bereinigte Copyright Section */}
          <div className="flex flex-col md:flex-row justify-between items-center pt-8 border-t border-white/10">
            <div className="text-white/90 mb-4 md:mb-0">
              <p>© 2024 IT for Youth Ghana. All rights reserved.</p>
            </div>

            <div className="text-white/90">
              <Link 
                to="/contact" 
                onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                className="hover:text-secondary transition-colors duration-300 font-medium"
              >
                Contact Us
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Scroll to top button */}
      <motion.button
        className="fixed bottom-8 right-8 w-12 h-12 bg-primary hover:bg-secondary rounded-full flex items-center justify-center text-white shadow-lg hover:shadow-xl z-50 transition-colors duration-300"
        whileHover={{ scale: 1.1 }}
        whileTap={{ scale: 0.9 }}
        onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
        initial={{ opacity: 0, scale: 0 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 1 }}
      >
        ↑
      </motion.button>
    </footer>
  )
}

export default Footer
