// src/components/layout/NavBar.vue
<template>
  <nav class="navbar">
    <div class="nav-container">
      <RouterLink to="/" class="nav-logo">
        <img src="@/assets/pictures/logo.png" alt="IT For Youth Ghana" class="logo-img">
        <span class="logo-text">IT For Youth Ghana</span>
      </RouterLink>
      
      <div class="nav-menu" :class="{ active: isMenuOpen }">
        <RouterLink to="/" class="nav-link" @click="closeMenu">Home</RouterLink>
        <RouterLink to="/programs" class="nav-link" @click="closeMenu">Programs</RouterLink>
        <RouterLink to="/about" class="nav-link" @click="closeMenu">About</RouterLink>
        <RouterLink to="/partner" class="nav-link" @click="closeMenu">Partner With Us</RouterLink>
        <RouterLink to="/news" class="nav-link" @click="closeMenu">News</RouterLink>
        <RouterLink to="/contact" class="nav-link" @click="closeMenu">Contact</RouterLink>
        <DonationButton />
      </div>
      
      <button class="nav-toggle" @click="toggleMenu" :aria-expanded="isMenuOpen">
        <span class="hamburger"></span>
      </button>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink } from 'vue-router'
import DonationButton from '@/components/DonationButton.vue'

const isMenuOpen = ref(false)

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}

const closeMenu = () => {
  isMenuOpen.value = false
}
</script>

<style scoped>
.navbar {
  background: rgba(10, 22, 40, 0.85);
  backdrop-filter: blur(20px) saturate(180%);
  box-shadow: 0 1px 20px rgba(10, 22, 40, 0.1);
  border-bottom: 0.5px solid rgba(255, 255, 255, 0.1);
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  width: 100%;
  z-index: 1000;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.nav-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 70px;
  width: 100%;
}

.nav-logo {
  display: flex;
  align-items: center;
  text-decoration: none;
  gap: 0.5rem;
}

.logo-img {
  height: 40px;
  width: auto;
  object-fit: contain;
}

.logo-text {
  font-size: 1.5rem;
  font-weight: 600;
  color: #ffffff;
  font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', system-ui, sans-serif;
  letter-spacing: -0.01em;
}

.nav-menu {
  display: flex;
  align-items: center;
  gap: 2rem;
}

.nav-link {
  text-decoration: none;
  color: rgba(255, 255, 255, 0.9);
  font-weight: 400;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  position: relative;
  font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif;
  letter-spacing: -0.005em;
  padding: 0.5rem 0.75rem;
  border-radius: 8px;
}

.nav-link:hover,
.nav-link.router-link-active {
  color: #ffffff;
  background: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(10px);
}

.nav-link.router-link-active::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  width: 4px;
  height: 4px;
  border-radius: 50%;
  background: #ffffff;
  box-shadow: 0 0 8px rgba(255, 255, 255, 0.5);
}

.btn-donate {
  background: linear-gradient(135deg, #0a1628 0%, #0c2461 100%);
  box-shadow: 0 4px 14px rgba(10, 22, 40, 0.2);
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 20px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif;
  letter-spacing: -0.01em;
}

.btn-donate:hover {
  background: linear-gradient(135deg, #0c2461 0%, #1e40af 100%);
  transform: translateY(-1px) scale(1.02);
  box-shadow: 0 6px 20px rgba(10, 22, 40, 0.3);
}

.nav-toggle {
  display: none;
  background: none;
  border: none;
  cursor: pointer;
  padding: 0.5rem;
}

.hamburger {
  display: block;
  width: 25px;
  height: 3px;
  background: #f9f8f9;
  transition: all 0.3s ease;
  position: relative;
}

.hamburger::before,
.hamburger::after {
  content: '';
  position: absolute;
  width: 25px;
  height: 3px;
  background: #f9f8f9;
  transition: all 0.3s ease;
}

.hamburger::before {
  top: -8px;
}

.hamburger::after {
  top: 8px;
}

@media (max-width: 1024px) {
  .nav-container {
    padding: 0 1.5rem;
  }
  
  .nav-menu {
    gap: 1.5rem;
  }
}

@media (max-width: 768px) {
  .nav-toggle {
    display: block;
  }
  
  .nav-container {
    padding: 0 1rem;
    height: 60px;
  }
  
  .navbar {
    height: 60px;
  }
  
  .nav-menu {
    position: fixed;
    left: -100%;
    top: 60px;
    flex-direction: column;
    background-color: rgba(26, 35, 56, 0.98);
    backdrop-filter: blur(20px);
    width: 100vw;
    height: calc(100vh - 60px);
    text-align: center;
    transition: left 0.3s ease;
    box-shadow: 0 10px 27px rgba(0,0,0,0.05);
    padding: 2rem 0;
    gap: 1.5rem;
    z-index: 999;
    overflow-y: auto;
  }
  
  .nav-menu.active {
    left: 0;
  }
  
  .nav-link {
    padding: 1rem 2rem;
    display: block;
    font-size: 1.2rem;
    width: 100%;
  }
  
  .btn-donate {
    margin: 2rem auto 0;
    padding: 1rem 2rem;
    font-size: 1.1rem;
  }
}

@media (max-width: 480px) {
  .nav-container {
    height: 60px;
    padding: 0 0.8rem;
  }
  
  .logo-text {
    font-size: 1.2rem;
  }
  
  .logo-img {
    height: 35px;
  }
  
  .nav-menu {
    top: 60px;
    padding: 1.5rem 0;
  }
  
  .nav-link {
    font-size: 1rem;
    padding: 0.8rem;
  }
}

</style>

// src/components/Navbar.tsx
import React, { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Link, useLocation } from 'react-router-dom'

const Navbar: React.FC = () => {
  const [isScrolled, setIsScrolled] = useState(false)
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const location = useLocation()

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50)
    }

    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  const navItems = [
    { name: 'Home', href: '/' },
    { name: 'About', href: '/about' },
    { name: 'Programs', href: '/programs' },
    { name: 'Impact', href: '/impact' },
    { name: 'Partner with Us', href: '/partners' },
    { name: 'Donate', href: '/donate' },
    { name: 'Contact', href: '/contact' },
  ]

  return (
    <motion.nav
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled 
          ? 'bg-primary shadow-lg' 
          : 'bg-primary/90'
      }`}
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      transition={{ duration: 0.8, ease: "easeOut" }}
    >
      <div className="container mx-auto px-6 py-6">
        <div className="flex items-center justify-between">
          {/* Logo */}
          <Link to="/" onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}>
            <motion.div 
              className="flex items-center"
              whileHover={{ scale: 1.05 }}
            >
              <img 
                src="/images/logo.png" 
                alt="IT for Youth Ghana" 
                className="h-16 w-auto object-contain"
              />
            </motion.div>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-8">
            {navItems.map((item, index) => (
              <motion.div
                key={item.name}
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <Link
                  to={item.href}
                  onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}
                  className={`transition-colors duration-300 font-medium ${
                    location.pathname === item.href
                      ? 'text-[#8fb2d6]'
                      : 'text-white hover:text-[#8fb2d6]'
                  }`}
                >
                  <motion.span whileHover={{ scale: 1.05 }}>
                    {item.name}
                  </motion.span>
                </Link>
              </motion.div>
            ))}
          </div>

          {/* Volunteer Button */}
          <Link to="/volunteer" onClick={() => setTimeout(() => window.scrollTo(0, 0), 100)}>
            <motion.button
              className="hidden md:block bg-accent hover:bg-accent/90 text-white px-6 py-3 text-sm rounded-xl font-semibold transition-colors duration-300"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.5 }}
            >
              Volunteer
            </motion.button>
          </Link>

          {/* Mobile Menu Button */}
          <button
            className="md:hidden text-white p-2"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          >
            <div className="w-6 h-6 relative">
              <motion.span
                className="absolute top-0 left-0 w-full h-0.5 bg-current origin-left"
                animate={{
                  rotate: isMobileMenuOpen ? 45 : 0,
                  y: isMobileMenuOpen ? 11 : 0,
                }}
                transition={{ duration: 0.3 }}
              />
              <motion.span
                className="absolute top-2.5 left-0 w-full h-0.5 bg-current"
                animate={{
                  opacity: isMobileMenuOpen ? 0 : 1,
                }}
                transition={{ duration: 0.3 }}
              />
              <motion.span
                className="absolute top-5 left-0 w-full h-0.5 bg-current origin-left"
                animate={{
                  rotate: isMobileMenuOpen ? -45 : 0,
                  y: isMobileMenuOpen ? -11 : 0,
                }}
                transition={{ duration: 0.3 }}
              />
            </div>
          </button>
        </div>

        {/* Mobile Menu */}
        <AnimatePresence>
          {isMobileMenuOpen && (
            <motion.div
              className="md:hidden mt-4 bg-primary rounded-2xl p-6"
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.3 }}
            >
              <div className="flex flex-col space-y-4">
                {navItems.map((item, index) => (
                  <motion.div
                    key={item.name}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                  >
                    <Link
                      to={item.href}
                      className={`block py-2 transition-colors duration-300 font-medium ${
                        location.pathname === item.href
                          ? 'text-[#8fb2d6]'
                          : 'text-white hover:text-[#8fb2d6]'
                      }`}
                      onClick={() => {
                        setIsMobileMenuOpen(false)
                        setTimeout(() => window.scrollTo(0, 0), 100)
                      }}
                    >
                      {item.name}
                    </Link>
                  </motion.div>
                ))}
                <Link to="/volunteer" onClick={() => {
                  setIsMobileMenuOpen(false)
                  setTimeout(() => window.scrollTo(0, 0), 100)
                }}>
                  <motion.button
                    className="bg-accent hover:bg-accent/90 text-white w-full py-3 mt-4 rounded-xl font-semibold transition-colors duration-300"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.3 }}
                  >
                    Volunteer
                  </motion.button>
                </Link>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.nav>
  )
}

export default Navbar
